name: fraction
version: 1.0.0.0

dependencies:
  - base

library:
  exposed-modules: Fraction
  source-dirs: src
  ghc-options: -Wall  -Wno-type-defaults

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - fraction
      - hspec
